### ISSUE TITLE
超长图片不显示，能否看看？

### ISSUE THREAD

**Issue by Paul1121** [idisfkj/Zoomable#1]
图片地址：http://ep.dzb.ciwong.com/kebi.jpg

**Comment by Paul1121** [comment]
图片高大于4096，可以显示吗？

**Comment by idisfkj** [comment]
@Paul1121 目前`fresco`加载最大图片尺寸是`4096*4096`，如果图片尺寸超过该标准是不能显示的。如果一定要显示的话，可以做特殊处理，对图片进行压缩，不请求原图

**Comment by Paul1121** [comment]
谢谢，
